first_number= int(input("Enter the First Number :"))
second_number = int(input("Enter the Second Number :"))
print("Addition : ",first_number + second_number)
print("Substraction : ",first_number - second_number)
print("Multiplication : ",first_number * second_number)
print("Division : ",first_number / second_number)
print("Floor division  : ",first_number // second_number)
print("Modulus : ",first_number % second_number)
print("Exponentiation : ",first_number ** second_number)